spring.application.name=vet_backend

spring.jpa.database=postgresql
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

# Database
spring.datasource.hikari.maximum-pool-size=8
spring.datasource.url=jdbc:postgresql://switchback.proxy.rlwy.net:50663/railway
spring.datasource.username=postgres
spring.datasource.password=ZdJRHUxFwpeKNbLysFxEkDGRvdiSJtlI

server.servlet.encoding.force=true

jwt.secret=VUwEyVBsYt9v7Zqs7TjeJmWUyZbLYcfrQyqe08f7MGVA9XkHa

# Toss Payments Test Keys
toss.client.key=test_ck_6bJXmgo28emAkj1ZvPpj8LAnGKWx
toss.secret.key=test_sk_pP2YxJ4K871YDdPYApPmVRGZwXLO
# ?? ?? ?? API ?? (???)
toss.url=https://api.tosspayments.com/v1/payments/confirm