spring.application.name=vet_backend

spring.jpa.database=postgresql
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
# Database
spring.datasource.hikari.maximum-pool-size=8
spring.datasource.url=jdbc:postgresql://shortline.proxy.rlwy.net:12310/railway
spring.datasource.username=postgres
spring.datasource.password=lMbhnJHoSygKLuCGaUdirUmBVSbaMNpD

server.servlet.encoding.force=true

jwt.secret=VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa