spring.application.name=vet_backend

spring.jpa.database=postgresql
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

# Database
spring.datasource.hikari.maximum-pool-size=8
spring.datasource.url=jdbc:postgresql://switchback.proxy.rlwy.net:50663/railway
spring.datasource.username=postgres
spring.datasource.password=ZdJRHUxFwpeKNbLysFxEkDGRvdiSJtlI

server.servlet.encoding.force=true

jwt.secret=VUwEyVBsYt9v7Zqs7TjeJmWUyZbLYcfrQyqe08f7MGVA9XkHa

## ? Timezone ?? ?? (Spring Boot 2.x/3.x ?? ??)
## Date/Time? ??? ? Spring? ??? Timezone? ??
#spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Seoul
#
## ? ?? ? ??? ????, ??? ?? ???? ?? ??
#server.local-time-zone=Asia/Seoul